version: "3.7"

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    expose:
      - 5432
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: [ "python3.9", "app.py" ]